module.exports = {
  COMMUNITY_CHAT: 'COMMUNITY_CHAT',
  USER_CONNECT: 'USER_CONNECT',
  USER_DISCONNECT: 'USER_DISCONNECT',
  MESSAGE_RECEIVE: 'MESSAGE_RECEIVE',
  MESSAGE_SEND: 'MESSAGE_SEND',
  TYPING: 'TYPING',
  REGISTER_USER: 'REGISTER_USER',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT',
  PRIVATE_MESSAGE: 'PRIVATE_MESSAGE',
  DESTROY: 'DESTROY',
  UPDATE_USER: 'UPDATE_USER'
};
